const express = require('express')
const router = express.Router()
const authRouter = require('./auth')
const usersAuth = require('./users')
const categoriesRouter = require('./categories')
const activitiesRouter = require('./activities')
const testimonyRouter = require('./testimony')
const membersRouter = require('./members')
const organizationRouter = require('./organizations')
const newsRouter = require('./news')
const contactRouter = require('./contacts')
const imagesRouter = require('./images')
const mailRouter = require('./mail')

router.use('/auth', authRouter)
router.use('/users', usersAuth)
router.use('/categories', categoriesRouter)
router.use('/testimonials', testimonyRouter)
router.use('/activities', activitiesRouter)
router.use('/members', membersRouter)
router.use('/organization', organizationRouter)
router.use('/news', newsRouter)
router.use('/contacts', contactRouter)
router.use('/images', imagesRouter)
router.use('/mail', mailRouter)

module.exports = router
