@host = {{$dotenv SERVER_HOST}}
@token = {{$dotenv TOKEN_TEST}}

@contentType = application/json

### Create an activity
POST {{host}}activities
x-access-token: {{token}}
Content-Type: {{contentType}}

{
  "name": "Actividad Agregada",
  "content": "Contenido Agregado"
}

### Update an activitiy
PUT {{host}}activities/3
x-access-token: {{token}}
Content-Type: {{contentType}}

{
  "name": "Actividad editada",
  "content": "Contenido editado"
}