@host = {{$dotenv SERVER_HOST}}
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsidXNlcklkIjo0LCJlbWFpbCI6InRlc3RAdGVzdC5jb20ifSwiaWF0IjoxNjUwNTUzNzYwLCJleHAiOjE2NTA1NTQzNjR9.3QwIpom_C0eA3R3-vKcuP15MBX6g9FupKrOvr_WDXTE
@contentType = application/json


### auth login
POST {{host}}auth/login
Content-Type: {{contentType}}
 
{
  "email":"test@test.com",  "password":"123456"
}

### auth register
POST {{host}}auth/register
Content-Type: {{contentType}}
 
{
  "firstName": "Usuario",
  "lastName": "UsuarioApellido",
  "email":"usuario01@test.com",  "password":"12345678"
}

### user edit
PUT {{host}}users/6
x-access-token:{{token}}
Content-Type: {{contentType}}
 
{
  "lastName":"www name edited",
  "firstName":"First name edited",
  "roleId": 3
}

### Categories
POST {{host}}categories
Content-Type: {{contentType}}
 
{
  "name":"CategoriaTest",
  "description":"Descripcion Categoria 01"
}