@host = {{$dotenv SERVER_HOST}}
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNjUwOTE0OTA4LCJleHAiOjE2NTA5MTU1MTJ9.lR0hGopX2xo2pRHW9wrrZhrWYM6g8lWsvTMdeykvhqg
@contentType = application/json


### auth login
POST {{host}}auth/login
Content-Type: {{contentType}}
 
{
  "email":"test@test.com",  "password":"123456"
}

### auth register
POST {{host}}auth/register
Content-Type: {{contentType}}
 
{
  "firstName": "UsuarioAgregado",
  "lastName": "UsuarioApellido",
  "email":"usuarioagregado@test.com",  "password":"Aa.12345678"
}

### user obtener todos
GET {{host}}users
x-access-token:{{token}}
Content-Type: {{contentType}}

### user edit
PUT {{host}}users/2
x-access-token:{{token}}
Content-Type: {{contentType}}
 
{
  "lastName":"Usuarioedited",
  "firstName":"First name edited",
  "roleId": 2
}
