@host = {{$dotenv SERVER_HOST}}
@token = {{$dotenv TOKEN_TEST}}

@contentType = application/json

### Create a categorie
POST {{host}}categories
Content-Type: {{contentType}}
 
{
  "name":"CategoriaTest",
  "description":"Descripcion Categoria 01"
}

### Get all categories
GET {{host}}categories
Content-Type: {{contentType}}

