@host = {{$dotenv SERVER_HOST}}
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsidXNlcklkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5jb20ifSwiaWF0IjoxNjUwNzAxNjEzLCJleHAiOjE2NTA3MDIyMTd9.0LVWKmXb9ErmW7nsWi64CHZG6edF-yQ8GAk0q8QC5aY

@contentType = application/json

### Get all members
GET {{host}}members
x-access-token: {{token}}

### Create a member
POST {{host}}members
x-access-token: {{token}}
Content-Type: {{contentType}}

{
  "name": "David"
}

### Update a member
PUT {{host}}members/1
x-access-token: {{token}}
Content-Type: {{contentType}}

{
  "name": "Carl"
}