@host = {{$dotenv SERVER_HOST}}
@token = {{$dotenv TOKEN_TEST}}

@contentType = application/json

### Get all members
GET {{host}}members
x-access-token: {{token}}

### Create a member
POST {{host}}members
x-access-token: {{token}}
Content-Type: {{contentType}}

{
  "name": "Un member",
  "image": "https://www.fom78.com.ar/img/category/github.svg"
}

### Update a member
PUT {{host}}members/9
x-access-token: {{token}}
Content-Type: {{contentType}}

{
  "name": "editado"
}

### Update an activitiy
DELETE   {{host}}activities/9
x-access-token: {{token}}