@host = {{$dotenv SERVER_HOST}}
@token = {{$dotenv TOKEN_TEST}}

@contentType = application/json

@id = {{$dotenv ID_TEST}}

### Get all news
GET {{host}}news
x-access-token: {{token}}

### Get a new by id
GET {{host}}news/1
x-access-token: {{token}}

### Delete a news
DELETE {{host}}news/2
x-access-token: {{token}}

### Create a member
POST {{host}}news
x-access-token: {{token}}ww
Content-Type: {{contentType}}

{
  "name": "News desde swagger4",
  "image": "https://images.unsplash.com/photo-1504711434969-e33886168f5c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
  "content": "Holaaaaaa",
  "categoryId":1
}