@host = {{$dotenv SERVER_HOST}}
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNjUwOTE1NTU5LCJleHAiOjE2NTA5MTYxNjN9.gRH99aHi9AMs66-KQeEpchDGs-6RMTnQH64janzNh_A

@contentType = application/json

### Get all news
GET {{host}}organization/1
x-access-token: {{token}}
