@host = {{$dotenv SERVER_HOST}}
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNjUwOTE1NTU5LCJleHAiOjE2NTA5MTYxNjN9.gRH99aHi9AMs66-KQeEpchDGs-6RMTnQH64janzNh_A

@contentType = application/json

### Get an organization
GET {{host}}organization/1
x-access-token: {{token}}

### Create an organization
POST {{host}}organization
x-access-token: {{token}}
Content-Type: {{contentType}}

{
  "name": "Organization name"
}

### Update an organization
PUT {{host}}members/1
x-access-token: {{token}}
Content-Type: {{contentType}}

{
  "name": "Somos Mas !!!!"
}