@host = {{$dotenv SERVER_HOST}}
@token = {{$dotenv TOKEN_TEST}}

@contentType = application/json

### Get all testimonials
GET {{host}}testimonials
x-access-token: {{token}}

### Create a testimony
POST {{host}}testimonials
Content-Type: {{contentType}}
 
{
  "name":"Un Testimonio agregado",
  "content":"Contenido testimonio"
}