@host = {{$dotenv SERVER_HOST}}
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsidXNlcklkIjoxLCJlbWFpbCI6InRlc3RAdGVzdC5jb20ifSwiaWF0IjoxNjUwNzAxNjEzLCJleHAiOjE2NTA3MDIyMTd9.0LVWKmXb9ErmW7nsWi64CHZG6edF-yQ8GAk0q8QC5aY

@contentType = application/json

### Get all testimonials
GET {{host}}testimonials
x-access-token: {{token}}

### Create a testimony
POST {{host}}testimonials
Content-Type: {{contentType}}
 
{
  "name":"Un Testimonio agregado",
  "content":"Contenido testimonio"
}